language: c
addons:
  apt:
    packages:
      - libelf-dev
script:
  - ./.travis/linux-build.sh
env:
  - KERNEL=4.10
  - KERNEL=4.11
  - KERNEL=4.12
  - KERNEL=4.13
  - KERNEL=4.16
  - KERNEL=4.17
compiler:
  - gcc
  - clang
notifications:
  email:
    - linux-sctp@vger.kernel.org
