language: c
script:
  - ./bootstrap
    && ./configure
    && make -j `/usr/bin/getconf _NPROCESSORS_ONLN`
  # ipv6 is not supported by Travis
  - make -C src/func_tests/ v4test
compiler:
  - gcc
  - clang
notifications:
  email:
    - linux-sctp@vger.kernel.org
